config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  resources :vendors
  resources :orders
  resources :shipments
end

app/models/address.rb
class Address < ActiveRecord::Base
  has_many :shipments
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :vendor
  has_one :shipment
  validates :number, uniqueness: { case_sensitive: false }
end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
  belongs_to :order
  belongs_to :address
  has_one :vendor, :through => :order
  accepts_nested_attributes_for :order
  accepts_nested_attributes_for :address
  validates :tracking_number, uniqueness: { case_sensitive: false }
  after_create :set_expected_delivery_date
  scope :urgent, -> { where.not(status: "normal") }


    def check_status
      # step1: get expected delivery date
      # step2: get current date
      # step3: if current date is one week before expected date
      # set as normal
      # if current date is equal or less than a day greater than
      # expected date then set as not normal.
      # if current date is greater than one day set to very late.
      start_date = Time.now.beginning_of_day
      dev_date = self.expected_delivery_date.beginning_of_day unless self.expected_delivery_date.blank?

      if start_date - 1.days <= dev_date
        self.status = "normal"
      elsif start_date - 1.days >= dev_date
        self.status = "not normal"
      elsif start_date - 2.days >= dev_date
        self.status = "very late"
      else
      end
      self.save
      self.status
    end


  private

    def set_expected_delivery_date
      # step1: get shipment vendor
      # step2: get all shipments from vendor with same zipcode
      # step3: get average time for delivering to that zipcode
      average_dates = vendor.shipments.select do |x|
        address.zipcode == x.address.zipcode && x.id != id
      end

      averages = average_dates.map do |average|
        if average.delivered_at == nil
        else
          (average.delivered_at - average.shipped_at)/ 1.day
        end
      end
      if averages.empty?
      else
        days = averages.compact.inject(0.0) { |sum,el| sum + el } / averages.size
        # step4: set add the average time to delivered_at time
        # and set as expected_delivery_date
        self.expected_delivery_date = Time.now + days.days
        self.save
      end
    end


end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :orders
  has_many :shipments, through: :orders

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @shipment = Shipment.new
    @order = @shipment.build_order
    @address = @shipment.build_address
    @orders = Order.includes(:vendor, :shipment).paginate(:page => params[:page], :per_page => 10)
    @late_shipments = Shipment.urgent.paginate(:page => params[:page], :per_page => 5)
  end
end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController

  def index
  end

  def show
    @shipment = Shipment.includes(:vendor).find(params[:id])
  end

  def new
    @shipment = Shipment.new
    @order = @shipment.build_order
    @address = @shipment.build_address
  end

  def create
    @shipment = Shipment.new(shipment_params)

    respond_to do |format|
      if @shipment.save
        format.html { redirect_to @shipment, notice: 'shipment was successfully created.' }
        format.json { render :show, status: :created, location: @shipment }
      else
        format.html { render :new }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end


  private

    def shipment_params
      params.require(:shipment).permit(
        :tracking_number,
        :status,
        :expected_delivery_date,
        :shipped_at,
        :delivered_at,
        order_attributes: [:id, :number, :vendor_id, :status ],
        address_attributes: [:id, :address1, :address2, :city, :zipcode, :state_name]
      )
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  def index
    @vendors = Vendor.all.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @vendor = Vendor.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/application/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
  <div class="container">
    <p class="text-muted"><span class="glyphicon glyphicon-copyright-mark" aria-hidden="true"></span> <%= Time.now.year %> Michael Hall</p>
  </div>
</footer>

app/views/application/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <ul class="nav nav-tabs">
      <li role="presentation" class="active"><a href="/">Home</a></li>
    </ul>
  </div>
</nav>

app/views/home/_form.html.erb
<%= form_for @shipment, :html => {:class => "form-horizontal"} do |f| %>
  <% if @shipment.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@shipment.errors.count, "error") %> prohibited this shipment from being saved:
      </h2>
      <ul>
      <% @shipment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :shipped_at, :value => Time.current %>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.text_field :tracking_number,
          {:class => 'form-control',
          :placeholder => 'Tracking Number'}
      %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.fields_for :order do |order|%>
        <%= order.hidden_field :status, :value => "active" %>
        <div class="form-group">
          <div class="col-sm-10">
            <%= order.text_field :number,
              {:class => 'form-control',
              :placeholder => 'Order Number'}
            %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-10">
            <%= order.collection_select :vendor_id,
              Vendor.all, :id ,:name,
              { include_blank: "Vendor" },
              { :class => "btn btn-secondary dropdown-toggle" }
            %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.fields_for :address do |address| %>
        <div class="form-group">
          <div class="col-sm-10">
            <%= address.text_field :address1,
              {:class => 'form-control',
              :placeholder => 'Address1'}
            %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-10">
            <%= address.text_field :address2,
              {:class => 'form-control',
              :placeholder => 'Address2'}
            %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-10">
            <%= address.text_field :city,
              {:class => 'form-control',
              :placeholder => 'City'}
            %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-10">
            <%= address.text_field :state_name,
              {:class => 'form-control',
              :placeholder => 'State'}
            %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-sm-10">
            <%= address.text_field :zipcode,
              {:class => 'form-control',
              :placeholder => 'Zipcode'}
            %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/home/_urgent.html.erb
  <h1 class='title-heading text-center'>Urgent Shipments</h1>
  <table class="table table-hover">
    <tr>
      <th>Tracking Number</th>
      <th>Delivery Status</th>
      <% @late_shipments.each do |shipment| %>
        <tr>
          <td>
            <%= link_to shipment.tracking_number, shipment_path(shipment) %>
          </td>
          <td class="<%= shipment.status.parameterize("_") %>">
            <%= shipment.status %>
          </td>
        </tr>
      <% end %>
    </tr>
  </table>
  <%= will_paginate @orders, renderer: BootstrapPagination::Rails %>

app/views/home/index.html.erb
<div class="page-header">
  <h1>ShipIt! <small>Track it</small></h1>
</div>
<div class="row">
  <div class="col-md-6">
    <h3>Create Shipment</h3>
    <%= render 'form' %>
  </div>
  <div class="col-md-6">
    <%= render 'urgent' %>
  </div>
</div>
<div class="row">
  <div class="jumbotron">
    <div class="container">
      <h1 class='title-heading text-center'>Active Orders</h1>
      <table class="table table-hover">
        <tr>
          <th>Vendor</th>
          <th>Order Number</th>
          <th>Tracking Number</th>
          <th>Delivery Status</th>
          <% @orders.each do |order| %>
            <tr>
              <td>
                <%= order.vendor.name %>
              </td>
              <td>
                <%= order.number %>
              </td>
              <td>
                <%= link_to order.shipment.tracking_number, shipment_path(order.shipment) %>
              </td>
              <td class="<%= order.shipment.check_status.parameterize("_") %>">
                <%= order.shipment.check_status %>
              </td>
            </tr>
          <% end %>
        </tr>
      </table>
      <%= will_paginate @orders, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ShipIt</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <%= render 'header' %>
    <div class='container'>
      <%= yield %>
    </div>
    <%= render 'footer' %>
  </body>
</html>

app/views/shipments/index.html.erb
<div class="page-header">
  <div class='row'>
    <div class='small-12 columns'>
      <h1 class='title-heading text-center'>Shipments</h1>
    </div>
  </div>
</div>

<table class="table table-hover">
  <tr>
    <th>Tracking Number</th>
    <th>Status</th>
    <th>Date Shipped</th>
    <% @shipments.each do |shipment| %>
      <tr>
        <td>
          <%= link_to shipment.tracking_number, shipment_path(shipment) %>
        </td>
        <td>
          <%= shipment.status %>
        </td>
        <td>
          <%= shipment.created_at %>
        </td>
      </tr>
    <% end %>
  </tr>
</table>
<%= will_paginate @shipments, renderer: BootstrapPagination::Rails %>

app/views/shipments/new.html.erb
<%= render '/home/form' %>

app/views/shipments/show.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Shipment</h1>
    <h3>Vendor: <%= @shipment.vendor.name %></h3>
    <h3>Order: <%= @shipment.order.number %></h3>
    <h3>Tracking Number: <%= @shipment.tracking_number %></h3>
    <h3>Status:
      <span class="<%= @shipment.check_status.parameterize("_") %>">
        <%= @shipment.check_status %>
      </span>
    </h3>
    <h3>Expected Delivery Date: <%= @shipment.expected_delivery_date.strftime("%B %d, %Y") %></h3>
  </div>
</div>

app/views/vendors/index.html.erb
<div class="page-header">
  <div class='row'>
    <div class='small-12 columns'>
      <h1 class='title-heading text-center'>Vendors</h1>
    </div>
  </div>
</div>

<table class="table table-hover">
  <tr>
    <th>Name</th>
    <% @vendors.each do |vendor| %>
      <tr>
        <td>
          <%= link_to vendor.name, vendor_path(vendor) %>
        </td>
      </tr>
    <% end %>
  </tr>
</table>
<nav aria-label="...">
  <ul class="pager">
    <li><a href="#">Previous</a></li>
    <li><a href="#">Next</a></li>
  </ul>
</nav>

app/views/vendors/show.html.erb
show.html.erb